# Created using wingetcreate 1.12.23.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Jellyfin.Server
PackageVersion: "12.2"
InstallerLocale: en-US
InstallerType: nullsoft
Scope: machine
ElevationRequirement: elevationRequired
UpgradeBehavior: install
ProductCode: JellyfinServer
AppsAndFeaturesEntries:
- DisplayName: Jellyfin Server 12.2
  ProductCode: JellyfinServer
InstallationMetadata:
  DefaultInstallLocation: '%ProgramFiles%\Jellyfin\Server'
Installers:
- Architecture: x64
  InstallerUrl: https://repo.jellyfin.org/files/server/windows/stable/v12.2/amd64/jellyfin_12.2_windows-x64.exe
  InstallerSha256: 0E6781D214FE384DB7325B70E6A499A830F0E3DBBAD9C5A4A8E722DCA5AE48FC
ManifestType: installer
ManifestVersion: 1.12.0
ReleaseDate: 2026-10-05
